- menu_name: "Website Services"

# - name: "Contact"
#   url: "/contact/"
#   title: "Contact"

# - name: "RSS"
#   url: "/feed.xml"
#   title: "Subscribe to RSS Feed"

# - name: "Atom"
#   url: "/atom.xml"
#   title: "Subscribe to Atom Feed"

- name: "Newsletter"
  url:  https://tinyletter.com/gkoeser
  title: "Sign up to stay informed"

- name: "sitemap"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
